name: Eff_subgraphs
channels:
  - pyg
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py39h5eee18b_0
  - chardet=5.2.0=py39hf3d152e_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h7633fee_0
  - cryptography=41.0.7=py39hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h4ba93d1_12
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.2=py39h84cc369_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.13.1=py39h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.0=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - greenlet=3.0.3=py39h3d6467e_0
  - icu=73.2=h59595ed_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=8.0.0=pyha770c72_0
  - importlib-resources=6.1.1=pyhd8ed1ab_0
  - importlib_metadata=8.0.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=1_h6e990d7_netlib
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py39hda80f44_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.78.3=h783c2da_0
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=3_h893e4fe_netlib
  - liblapacke=3.9.0=3_h893e4fe_netlib
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h753d276_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-base=3.8.0=py39he9076e7_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py39h06a4308_0
  - numpy=1.26.2=py39h5f9d8c6_0
  - numpy-base=1.26.2=py39hb5e798b_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.3.1=h4ab18f5_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py39hddac248_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py39h444a776_1
  - pip=23.3.1=py39h06a4308_0
  - pixman=0.42.2=h59595ed_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycairo=1.25.1=py39hc92de75_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.1.2=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cluster=1.6.3=py39_torch_2.1.0_cu118
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py39_torch_2.1.0_cu118
  - pytorch-sparse=0.6.18=py39_torch_2.1.0_cu118
  - pytorch-spline-conv=1.2.2=py39_torch_2.1.0_cu118
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=26.0.3=py39ha1047a2_0
  - rdkit=2023.09.3=py39hce5ca95_1
  - readline=8.2=h5eee18b_0
  - reportlab=4.0.8=py39hd1e30aa_0
  - requests=2.31.0=py39h06a4308_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py39h1128e8f_0
  - scipy=1.5.3=py39hf3f25e7_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.24=py39hd1e30aa_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.1.0=py39
  - tornado=6.4.1=py39hd3abc70_0
  - tqdm=4.65.0=py39hb070fc8_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=1.26.18=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - appdirs==1.4.4
      - click==8.1.7
      - docker-pycreds==0.4.0
      - easydict==1.11
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.41
      - littleutils==0.2.2
      - ogb==1.3.6
      - outdated==0.2.2
      - protobuf==4.25.2
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - smmap==5.0.1
      - torch-geometric==2.4.0
      - wandb==0.16.2
prefix: /home/guy_b/miniconda3/envs/Eff_subgraphs